<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Authors>Ethan Henderson (zbee)</Authors>
        <Company>Team Wrath</Company>
        <Description>Everything you need to work with Wrath Combo's IPC</Description>

        <Configurations>Debug;Release</Configurations>
        <Platforms>x64</Platforms>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <NoWarn>MSB3277;CS8632;CS8602;CS8604</NoWarn>

        <TargetFramework>net9.0-windows</TargetFramework>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    </PropertyGroup>

    <PropertyGroup>
        <DalamudLibPath>$(MSBuildThisFileDirectory)..\..\..\TC_ok\_dalamud_api13\</DalamudLibPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Dalamud">
            <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="FFXIVClientStructs">
            <HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

</Project>
